apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: label-configmaps
spec:
  remediationAction: inform
  severity: low
  object-templates-raw: |
    {{- range (lookup "v1" "ConfigMap" "my-configmaps" "").items }}
    {{- if and .data.model (contains "Mustang" .data.model) }}
    - complianceType: musthave
      recordDiff: InStatus
      objectDefinition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: {{ .metadata.name }}
          namespace: {{ .metadata.namespace }}
          labels:
            ford.com/model: Mustang
    {{- end }}
    {{- end }}
