apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: operatorpolicy-gatekeeper-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  subscription:
    name: gatekeeper-operator-product
    namespace: openshift-operators
  upgradeApproval: Automatic
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: gatekeeper
spec:
  remediationAction: enforce
  severity: high
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: operator.gatekeeper.sh/v1alpha1
        kind: Gatekeeper
        metadata:
          name: gatekeeper
        spec:
          audit:
            logLevel: INFO
            replicas: 1
          validatingWebhook: Enabled
          mutatingWebhook: Disabled
          webhook:
            emitAdmissionEvents: Enabled
            logLevel: INFO
            replicas: 2
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: gatekeeper-status
spec:
  remediationAction: inform
  severity: high
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Pod
        metadata:
          namespace: openshift-gatekeeper-system
          labels:
            control-plane: audit-controller
        status:
          phase: Running
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Pod
        metadata:
          namespace: openshift-gatekeeper-system
          labels:
            control-plane: controller-manager
        status:
          phase: Running
